---
on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  java_tests:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/unit-tests')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read deployment file
        id: deployment_file
        run: |
          echo 'DEPLOY_CONFIG_JSON<<EOF' >> GITHUB_OUTPUT
          cat ./deploy_config.json >> GITHUB_OUTPUT
          echo 'EOF' >> GITHUB_OUTPUT
      - name: Run tests with supplied configuration
        run: |
          echo 'Running ${{ fromJson(steps.deployment_file.outputs.DEPLOY_CONFIG_JSON).tests.java.name }}'
          ./gradlew ${{ fromJson(steps.deployment_file.outputs.DEPLOY_CONFIG_JSON).tests.java.task }}
