---
on:
  pull_request: ~
  workflow_dispatch:
  issue_comment:
    types: [created, edited, deleted]

permissions: read-all

jobs:
  java_tests:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/unit-tests')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get an entry with a variable that might contain dots or spaces
        id: get_username
        uses: mikefarah/yq@master
        with:
          cmd: yq deploy_config.yaml
      - name: Run tests with supplied configuration
        run: |
          echo 'Running ${{ fromJson(steps.deployment_file.outputs.result).tests.java.name }}'
          ./gradlew ${{ fromJson(steps.deployment_file.outputs.result).tests.java.task }}
