---
on:
  issue_comment:
    types: [created, edited, deleted]

permissions: read-all

jobs:
  java_tests:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/unit-tests')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Get an entry with a variable that might contain dots or spaces
        id: task_name
        uses: mikefarah/yq@master
        with:
          cmd: yq '.tests.java[0].task' deploy_config.yaml
      - name: Run tests with supplied configuration
        run: |
          echo './gradlew ${{ steps.task_name.outputs.result }}'
